In [1]:
# we can use list data structure but i want to use numpy arrays to do a little bit more coding

In [2]:
import random

In [3]:
import numpy as np

In [4]:
# this function is used to generate random numpy arrays receiving the size of the numpy array and the range 
def RandomArrayGenerator(size, rangeBeginning, rangeEnding):
    tempArr = np.zeros(size) # generating an array with all zero as elements
    for i in range(tempArr.shape[0]): #iterating through the array to change the elements to random integers as elements
        tempArr[i] = random.randint(rangeBeginning, rangeEnding)
    return tempArr

In [5]:
array1 = RandomArrayGenerator(5, 1, 10)
array1

array([ 4.,  2.,  2., 10.,  7.])

In [6]:
array2 = RandomArrayGenerator(5, 1, 10)
array2

array([ 4.,  7., 10.,  5.,  9.])

In [7]:
# this function is used to merge two arrays 
# although i couldve used np.concatenate to stick the arrays together, i decided to do it on my own from scratch 
# and i know that its not that optimized but it was worthy coding again like old days i really enjoyed it 
# i also couldve used list as the data structure but i found myself interested in make the task a little bit trickier so i used 
# numpy arrays 
# duplicate checking and sorting isnt done yet

def mergeTwoArrays(first_array, second_array):
    first_array_shape = first_array.shape[0] # size of the first array (supposing its 1D)
    second_array_shape = second_array.shape[0] # size of the second array (supposing its 1D)
    size = first_array_shape + second_array_shape # size of the whole array including two arrays
    mergedArray = np.zeros(size) # initializing a new array to put those arrays together 
    
    for i in range(first_array_shape): #iterating through the first array and adding its elements to the new array 
        mergedArray[i] = first_array[i]
    
    for j in range(second_array_shape):
        mergedArray[first_array_shape + j] = second_array[j] #doing the same as above 
    
    return mergedArray

In [8]:
mergedArray = mergeTwoArrays(array1, array2)
mergedArray
#as you can see we have the elements of each array all together but there are a lot of duplicate values and its not sorted

array([ 4.,  2.,  2., 10.,  7.,  4.,  7., 10.,  5.,  9.])

In [9]:
# still dont want to use any method like  np.unique() so i do it all by myself like what we did in basic programming using C++
# this function drops the duplicates and return the cleaned numpy array
# you may think its getting complicated but trust me coding is fun 

def dropDuplicates(array):
    size = array.shape[0] #SIZE OF OUR NP ARRAY
    newArr = np.array([array[0]])  # Start with the first element and creating a new array and initializing its first element
    for i in range(1, size): # checking the indexes 1 to last because 0 is already iterated 
        temp = array[i] #temp
        for j in range(newArr.shape[0]): #iterating the array to check if there is any equal element, if not appending the value
            if temp == newArr[j]:
                break
        else:
            newArr = np.append(newArr, temp)

    return newArr

In [10]:
dropDuplicates(mergedArray) # checking to see if the function above worked 

array([ 4.,  2., 10.,  7.,  5.,  9.])

In [11]:
# i want to use this function to find the minimum value and its index 
def minFinder(array):
    min_val = array[0]
    min_index = 0
    for i in range(1, array.shape[0]):
        if array[i] < min_val:
            min_val = array[i]
            min_index = i
    return min_val, min_index

In [12]:
minFinder(dropDuplicates(mergedArray)) #checking my function to see if it works 

(2.0, 1)

In [13]:
# dont want to use np.sort() in this task so ...
# we do the sorting with the help of minimum finder function i wrote above
def Sorter(array):
    sortedArray = np.zeros(array.shape[0])  # initialize an empty array of the same size
    array_copy = np.copy(array)  # creating a copy to avoid modifying the original array
    
    for i in range(array.shape[0]):  # iterate for each element in the original array
        min_val, min_index = minFinder(array_copy)
        sortedArray[i] = min_val  # store the minimum value in sorted array
        array_copy = np.delete(array_copy, min_index)  # remove the minimum element
    
    return sortedArray

In [14]:
Sorter(dropDuplicates(mergeTwoArrays(array1, array2)))

array([ 2.,  4.,  5.,  7.,  9., 10.])

In [15]:
# i guess i did everything modular

In [16]:
# function to merge, remove duplicates and sort
def mergeDropSort(array1, array2):
    mergedArray = mergeTwoArrays(array1, array2)  # merge the arrays
    uniqueArray = dropDuplicates(mergedArray)  # remove duplicates
    sortedArray = Sorter(uniqueArray)  # sort the array
    return sortedArray

In [17]:
# using the final function which had everything inside it
array1 = RandomArrayGenerator(5, 1, 10)
array2 = RandomArrayGenerator(5, 1, 10)

finalSortedArray = mergeDropSort(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Final Merged, Unique, and Sorted Array:", finalSortedArray)

Array 1: [4. 6. 1. 7. 9.]
Array 2: [10. 10.  4.  8.  9.]
Final Merged, Unique, and Sorted Array: [ 1.  4.  6.  7.  8.  9. 10.]
